### ISSUE TITLE
Throws above 9 in sync or multiplex siteswap

### ISSUE THREAD

**Issue by hattom** [yDgunz/gunswap#1]
Maybe I'm missing something, but I don't seem to be able to specify a sync or multiplex pattern with a throw of a or higher.

patterns that work: a a8 (6,2) (8,2) (6x,2x) [80] [9]
patterns that don't work: (a,2) (ax,2x) [a0] [a]

Error message for the sync problem is: Cannot determine number of props
Error message for the multiplex problem is: No prop available to toss at beat 0

**Comment by yDgunz** [comment]
Thanks for the bug report! Looks like any non vanilla siteswaps with tosses >= 'a' don't work. I think I found the issue so I'm gonna push the fix later.
