### ISSUE TITLE
Getting Error: "Unable to calculate bounce path"

### ISSUE THREAD

**Issue by bblodfon** [yDgunz/gunswap#19]
I don't know if this is normal or not but when I try 1B or 3B or 4B or 9B{HF}45 as "Siteswap" and press "Juggle", I get the error mentioned above. The 3B{HF} works though or the simple 9B45 or even 2B. The last case is a little tricky as I would have wanted to see 2 as active and bounced (not only as a simple inactive "2"). Also I tried the 2B in a siteswap as 42B3 and 12B345 and got the same error!

**Comment by yDgunz** [comment]
The "Unable to calculate bounce path" error message shows up when a pattern calls for a bounce that cannot be performed within the time constraints of the beat duration and dwell ratio. Consider your example 9B{HF}45, presumably you left the default beatDuration of .28? Say the dwellRatio is 1 (just to make things simple, though I think the default is actually .8 or something like that). Then the 9 toss has to take .28*(9-1)=2.24 seconds. You set the bounce to be a "hyperforce" bounce which means that it is thrown down and caught while it is still rising. This is not possibly within 2.24 seconds. So you have to tweak the beatDuration and dwellRatio a bit to find something that works. Try 9B{HF}45 with a beatDuration of .08, it looks kind of silly and I think HF really isn't the best bounce type for this pattern. I rather like 9B{HL}45 with a beatDuration of .28 - http://www.gunswap.co/?patternId=582a7729d20b260013803151. Note that HL stands for "hyperlift" which means that it is thrown up and caught while it is falling. I adopted this terminology from juggling lab, not sure how standardized it is throughout the (bounce) juggling community. 

Regarding the active 2's, you need to write them as 2A. So 42AB{HF}3 would be 423 with a bounce: http://www.gunswap.co/?patternId=582a7829d20b260013803154. This is a scenario where I think the hyperforce bounce works really nicely.

I've thought of providing some lookup tables or a "find best beatDuration" feature to make this easier to do. Hopefully this was helpful, let me know if you have any questions!

**Comment by bblodfon** [comment]
Thanks for the explaining - I understand it now. Still the thing that when you enter "3B" or "5B" and you get the above error still remains - what I mean is you can't expect someone to start messing with the beatDuration just to see a 3 ball cascade bounced or expect from him to enter the "standard" way which is juggled: 3B{HF} or 5B{F}?

When searching siteswaps and someone wants to see if some throw can be bounced some way he just enters B after that throw: so, it would be a good idea to do what Juggling Lab does in that case - that is  when a specified bounced throw is not possible, your programm _should adjust the throw style_ (HL, L, F, HF) to the one appropiate in order to calculate the bouncing path (and also get a message of the "correct" siteswap notation used) - it would be really great because it would tell the person what kind of bounce he/she should use to get that trick.

I also saw that in bouncing juggling there is the _number of bounces_ which can also be affected here but you don' t support that, correct?

**Comment by yDgunz** [comment]
That's a good point, you should be able to write "5B" and have it just work. I'm sure I can set it up so that it chooses smart defaults to avoid having the user tweak the bounce types and beat duration.

I can support number of bounces, as well as bouncing against user defined surfaces and the order in which the bounces occur! I can explain more later, perhaps write an article explaining how it works in better detail. I've been personally very busy the last week or so, and will be for a month or two, so updates in the near term may be few and far between. Thanks for the interest and feedback.

**Comment by yDgunz** [comment]
Modified the siteswap parser to apply a smarter default bounce type. Seems to work nice, try just putting in 3B or 5B and you'll see a working bounce pattern. I think 42AB3 looks particularly nice as well.

Regarding number of bounces, you need to write it like 3B{2}. If you want to specify the bounce type you do it before the number of bounces, like 3B{F2}. Check out this pattern demonstrating double bounces: http://www.gunswap.co/?patternId=583859da12ff810013262842.
