### ISSUE TITLE
Passing Notation Issue

### ISSUE THREAD

**Issue by bblodfon** [yDgunz/gunswap#3]
Hi yDgunz!

First of all, excellent work on this project. It is a modern, up-to-date siteswap generator+animator with a lot of features not found anywhere else. 
Just yesterday, I was searching for a good passing animator and found 2 of them: JoePass! and Jongl. They were difficult to use and I thought that maybe your Gunswap could also do passes. Amazed, I found out that it supports it, but I ran into this issue:

In your "Advanced Mode Syntax", "Pattern" section, you state that using "<3|3>" or "<3P|3P>" would create the appropiate animations, but instead I get "! Number of jugglers doesn't match".
Also, I saw that on the "Help" Tab, you have a "Passing siteswap - 4 count passing": that generates a siteswap of <3|3><3|3><3|3><3P|3P> and a proper animation. But when I try to put this same value in the siteswap section, I get the same error as above and nothing is animated!
Am I doing something wrong in the passing notation or is this a bug?

Also, it would be great if your Gunswap could understand prechac notation (I don't know if you plan on doing this in the future), e.g. insert only this: 333P in the Siteswap section and get the same animation results as above!

**Comment by yDgunz** [comment]
Hey @bblodfon, thanks for the kind words and the helpful issue! The problem is you are not setting all the jugglers' position/rotation on line 6 of the advanced input textarea. Try setting it to 0 1 0 0 -1 3.14 to have two jugglers separated by 2 meters in the z-axis and facing each other. I updated the syntax help page to better clarify this.

I don't know much about prechac notation but it sounds like a much cleaner way to represent passing patterns. I don't much like representing a simple 4 count as <3|3><3|3><3|3><3P|3P>, but it's more consistent with the Juggling Lab syntax which was kind of my starting point. Do you have any helpful resources that explain prechac?

I appreciate the feedback, if you have any other thoughts on cool features for the animator let me know.

**Comment by bblodfon** [comment]
Ok I got it now! Though I believe that it would be better to have as a default the starting positions of the two, three, etc jugglers - for the notation you are using the number of "|" + 1 equals the number of jugglers, so you could get it from there and preset the positions. Of course then comes the question of how to place the figures depending on who passes to who (angles mostly) and it becomes a little complicated I guess... Also I am thinking about how many jugglers we could fit in your simulation :)

The only reason I am stating this is because Gunswap (and any juggling animator) *should be intuitive* towards the average juggler user - he that knows a little siteswap notation of course :). What I mean is that someone should be able to write some numbers and get an animation (not trying to figure how to place the jugglers on a (x,z) plane + rotation - but also having the ability to do so afterwards if he wants to - which Gunswap provides) or generate some passing numbers and "play" them instantly.

Prechach notation is the most usefull to the average juggler because it derives from the siteswap notation very easily. Some usefull info you can find at:
1. [PrechachThis](http://www.prechacthis.org/) . This is sadly no animator but it generates files for input to JoePass! in prechac notation. The source code is also in github. You could use this easily I suppose!
2. [PrechacArticleOnSymmetricPatterns](http://www.passingdb.com/articles.php?id=13). This article tell us how to generate symmetric patterns from simple siteswap notation. The prechac passing bible if you like!
3. Gandini has done a terrific work making the prechac system more popular and has made a categorization of the patterns, e.g. see this catalog: [symmetric_patterns_Gandini](http://www.owenreynolds.net/notation/Symmetric_patterns2.pdf#5983DD.pdf)

I hope I helped a little.
