### ISSUE TITLE
Question: renderMode = '2D'?

### ISSUE THREAD

**Issue by geniusupgrader** [yDgunz/gunswap#37]
Is the renderMode 2D still working?
What does it do?
If enabled nothing is shown...
Can it be dismissed to reduce/recfactor code base?

**Comment by yDgunz** [comment]
Oh yeah, that's super old. Had visions of having a 2D vs. 3D mode, but ultimately just preferred only offering the 3D mode.

**Comment by geniusupgrader** [comment]
Well, when in the 3d view and the camera is locked, pointing exactly from front, than it is actually a (faked) 2d view. This would have a real benefit, because I do not quite like the up and down camera control (to see the juggler from above or from the bottom). So this would be a nice addition (always the right angle, parrallel to ground, just zooming and panning). Maybe I open a new feature request in this regard.

**Comment by geniusupgrader** [comment]
Then maybe this old code base could be reused

**Comment by geniusupgrader** [comment]
Closing this in favor of #42
