### ISSUE TITLE
Dwellpath ignores values with synchronous siteswaps

### ISSUE THREAD

**Issue by topox** [yDgunz/gunswap#5]
Hello yDgunz!

With synchronous siteswaps the dwellPath is difficult to use, since every second pair of values is ignored. Consider the siteswap (2,2)(2x,2x).

With 
dwellPath=(30)(30).(30)(30).(0)(0).(0)(0)
the hands always stay at (30), while with 
dwellPath=(30)(30).(30)(30).(99)(99).(99)(99).(0)(0).(0)(0).(99)(99).(99)(99)
the 99's are ignored, and it does what I would expect from the first dwellPath, i.e., for the (2x,2x) the hands meet in the middle.

Thanks for gunswap. It is very nice :-)

**Comment by yDgunz** [comment]
Thanks for reporting this issue. You're right that it does appear to be skipping dwell paths, not sure why that is. I'll have to take a look and try to address in the next release.

Thanks for the kind words and helpful bug report!

**Comment by yDgunz** [comment]
Fixed this in v17.
