### ISSUE TITLE
How to do that?

### ISSUE THREAD

**Issue by Retardeded** [yDgunz/gunswap#52]
Im not that bad at this siteswap notation stuff etc, but still I have no idea, how to describe in this simulator notation trick from this video https://www.youtube.com/watch?v=vLN43P2Icpw&t=467s .
I mean this synchronous 4 ball trick.

**Comment by geniusupgrader** [comment]
Should be SprungCascade: https://libraryofjuggling.com/Tricks/4balltricks/SprungCascade.html
Siteswap is: (6x, 2x)*
